// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeMusic
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeMusic.04d1ad52-13df-4ac4-9168-ed56772c5b3b";
        public const string Name = "Code Music";
        public const string Description = @"VSIX Music player in Visual Studio";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Ante Vučić";
        public const string Tags = "";
    }
}
