// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeMusic
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CodeMusicString = "e29a49be-b568-4906-afcd-82eff11b153f";
        public static Guid CodeMusic = new Guid(CodeMusicString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int PlayOrPause = 0x0100;
        public const int cmdNext = 0x0102;
        public const int cmdPrevious = 0x0101;
    }
}